baseurl: "/Portfolio"
url: "https://strangeplatypus.github.io"

title: "Portfolio de Julie Poignant"
description: Découvrez le portfolio de Julie Poignant, développeur web front-end. Explorez ses projets innovants et son expertise en création de sites web modernes.
author-name: Julie Poignant